[theme]
base = "light"
primaryColor = "#163B67"
backgroundColor = "#F6F8FB"
secondaryBackgroundColor = "#F0F4F8"
textColor = "#0B1220"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true

[browser]
gatherUsageStats = false
