[theme]
base = "light"
primaryColor = "#F54E00"
backgroundColor = "#F7F7F4"
secondaryBackgroundColor = "#FAFAF7"
textColor = "#26251E"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true

[browser]
gatherUsageStats = false
